version: '3'

services:
  loki:
    image: grafana/loki:2.7.3
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.7.3
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs:/app/logs
    command: -config.file=/etc/promtail/promtail-config.yml
